### ISSUE TITLE
两列布局，未知高度的一列怎么和另一列保持同样的高度？

### ISSUE THREAD

**Issue by xixigiggling** [Mars-Front-End/Barbecue#1]
**描述**： 两列布局，但左边一列是ul元素形成的导航栏，右边一列是主要的内容区，父元素的高度是随着内容区高度变化的，但是导航栏的那一列不能撑满整个父元素

**代码**：

```html
 <div class="category">
        <ul class="cate_menu">
            <li>
            <!-- more -->
            </li>
        </ul>
        <div class="cate_pop">
            <!-- more -->
        </div>
 </div>
```
```css
/*有部分省略*/
.category {
    overflow: hidden;
}
.category .cate_menu {
    overflow: hidden;
    padding: 10px 0;
    width: 156px;
    float: left;
    background-color: #f5f5f5; /*颜色特意加上，以便区分*/
    color: #636363;
}
.category .cate_pop {
    float: left;
    width: 1050px;
    height: 371px;
    border: 1px solid #f7f7f7;
    padding: 10px 0;
    background-color: #fff;
    box-shadow: 2px 0 5px rgba(0, 0, 0, .3);
}
```
**贴图**：

如图：左边的高度只有实际的高度，不能撑满

![fillLeftProblem](https://github.com/xixigiggling/markdownImgs/raw/master/res/questions/fillLeft.png)
