### ISSUE TITLE
做可滑动的水平导航栏时，怎么让固定宽度的父元素下的子元素(要滚动的item)不自动折行呢？

### ISSUE THREAD

**Issue by xixigiggling** [Mars-Front-End/Barbecue#3]
**描述**： 移动端一个常见的需求，可滑动的水平导航栏，但是在做的时候，发现父元素固定视口后，子元素超过内容的宽度一定会换行的...，这样的话水平的滑动该怎么做呢？

**代码**：

```html
<div class="wrapper">
        <ul class="content">
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
            <li class="item">hello</li>
       </ul>
</div>
```
```css
ul {
    margin: 0;
    padding: 0;
}
.wrapper {
    width: 300px;
    height: 50px;
    border: 1px solid grey;
    /* overflow: scroll; */
}
.wrapper .content {
    font-size: 0;
}
.wrapper .content .item {
    display: inline-block;
    font-size: 12px;
    padding: 19px 10px;
}
```

**贴图**：

![](https://github.com/xixigiggling/markdownImgs/raw/master/res/questions/slide.png)

**Comment by xixigiggling** [comment]
**解决**： 发现只有在ul元素上加上指明固定宽度的时候，才可以变成水平的导航栏...

```css
.wrapper .content {
    /* 一定要设这个固定的宽度才可以。。。 */
    width: 500px;
    font-size: 0;
}
```

在高仿饿了么的案例中也找到了相应的佐证：
```js
_initPics() {
	if (this.seller.pics) {
	  let picWidth = 120;
	  let margin = 6;
	  let width = (picWidth + margin) * this.seller.pics.length - margin;
	  // 一定要加上宽度
	  this.$refs.picList.style.width = width + 'px';
	  this.$nextTick(() => {
	    if (!this.picScroll) {
	      this.picScroll = new BScroll(this.$refs.picWrapper, {
		scrollX: true,
		eventPassthrough: 'vertical'
	      });
	    } else {
	      this.picScroll.refresh();
	    }
	  });
	}
}
```

**Comment by xixigiggling** [comment]
**新增**：

在张鑫旭大神的这篇文章中，似乎无意找到了问题的答案？：[理解CSS3 max/min-content及fit-content等width值](https://www.zhangxinxu.com/wordpress/2016/05/css3-width-max-contnet-min-content-fit-content/)：


> ... // 列举三种情况
> 
> 上面1~3情况，**除非有明确的width相关设置，否则尺寸都不会主动超过容器宽度的**，但是，存在一些特殊情况，例如，连续的英文数字，好长好长；或者**内联元素被设置了white-space:nowrap**，则表现为一江春水向东流。
> 
> ... // 继续balabala

这就留下一个思考：如果把水平导航的每个菜单栏用`span`再加上`white-space:nowrap`那不就实现了可以水平超过容器宽度？

**实验**：

```html
 <div class="line">
	<span class="block">川菜</span>
	<span class="block">湘菜</span>
	<span class="block">粤菜</span>
	<span class="block">鲁菜</span>
	<span class="block">其他</span>
</div>
```

```css
.line {
	width: 300px;
	line-height: 50px;
	display: inline-block;
        /* 注意是父元素加上*/
	white-space: nowrap;
	background: #f5f5f5;
	border: 1px solid gray;
}
.line .block {
	font-size: 20px;
	padding: 15px 20px;
}
```

结果如图：

![](https://github.com/xixigiggling/markdownImgs/raw/master/res/questions/span_nav_horizontal.png)
